openapi: "3.0.0"
info:
  title: OJP Meta Service
  version: 1.0.0
paths:
  /:
    get:
      operationId: helloworld
      summary: get hello world
      responses:
        "200":
          description: |-
            200 response
          content:
            application/json:
              schema:
                type: string
                example: "Hello world!"
                
